### ISSUE TITLE
Minification suggestions

### ISSUE THREAD

**Issue by hellp** [andyet/ConsoleDummy.js#1]
Hi,

especially in the full version you may save some bytes using:

```
methods = "log,dir,...".split(",");
```

And instead of using i you could .pop the function names out of the array; and change the assignment from x[f] || (x[f] = y) to x[f] = x[f] || y which allows you to safely omit the parentheses:

```
while (func = methods.pop()) {
    con[func] = con[func] || dummy;
}
```

btw: Why not just go with the structure the Closure Compiler suggests? Using the for loop and function c () {} (without the var)? It's not the most beautiful code but not cryptic either, so if we're up for the minimal solution, I think using this structure in the not minified code is okay. The minifier only had to short the variable names and whitespace then.

```
(function (con) {
    // the dummy function
    function dummy() {}
    for (// console methods that may exist
         var methods = "assert,count,debug,dir,dirxml,error,exception,group,groupCollapsed,groupEnd,info,log,markTimeline,profile,profileEnd,time,timeEnd,trace,warn".split(","),
             func;
         // Iteration statement and break condition in one step;
         func = methods.pop();) {
        con[func] = con[func] || dummy
    }
}(window.console || (window.console = {})));
```

**Comment by HenrikJoreteg** [comment]
Hey thanks! I've implemented your suggestions. Very nice!
